# Generated by Django 4.2.5 on 2023-11-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0002_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'permissions': [('permiso especial', 'Puede Leer y Editar Modelos')], 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
    ]
