# Generated by Django 4.2.5 on 2024-01-10 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctrl_comb', '0004_alter_modelo_options_mark_estado_mark_fc_mark_fm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('register', models.CharField(db_column='Matricula Vehículo', help_text='Matricula Vehículo', max_length=50)),
                ('year', models.PositiveSmallIntegerField(help_text='Año del Vehículo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ctrl_comb.modelo')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vehículos',
                'db_table_comment': 'Vehículos',
            },
        ),
    ]
