# Generated by Django 4.2.5 on 2024-03-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0005_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('MOT', 'Motocicleta'), ('CAP', 'Caponera'), ('SUV', 'Camioneta (SUV)'), ('PIK', 'PickUp'), ('SED', 'Sedán'), ('TAX', 'Taxi'), ('MIC', 'Microbus'), ('BUS', 'Autobus'), ('CAM', 'Camion')], default='SED', max_length=3),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='unidad_medida',
            field=models.IntegerField(choices=[(1, 'Galones'), (2, 'Litros')], default=1),
        ),
    ]
